development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=event_schedule_db user=khanh_admin password=SomeSecretPassword sslmode=disable
  dir: migrations

production:
  dialect: postgres
  datasource: dbname=event_schedule_db sslmode=disable
  dir: migrations
